# Generated by Django 5.1.5 on 2025-02-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='image',
            field=models.ImageField(upload_to='gadgets/images'),
        ),
    ]
