# Generated by Django 5.1.5 on 2025-02-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0002_alter_gadget_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gadget',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='gadget',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gadget',
            name='price',
        ),
        migrations.AddField(
            model_name='gadget',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gadget',
            name='comparisons_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gadget',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gadget',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='category',
            field=models.CharField(choices=[('mobiles', 'Mobiles'), ('tab', 'Tablets'), ('laptop', 'Laptops'), ('computers', 'Computers')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='ram',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='storage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
