# Generated by Django 5.1.5 on 2025-02-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0003_remove_gadget_brand_remove_gadget_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadget',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gadget_images/'),
        ),
    ]
