# Generated by Django 5.1.5 on 2025-02-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0005_review_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadget',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gadget',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
