# Generated by Django 5.1.5 on 2025-02-09 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0006_gadget_brand_gadget_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='gadget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gadgets.gadget'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
